### ISSUE TITLE
Error {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_eth0'"}

### ISSUE THREAD

**Issue by wpoosanguansit** [mrlesmithjr/ansible-rpi-k8s-cluster#15]
Hi,

Thank you for your help.  I did make sure to set the jump ip and the correct range following the doc but I keep getting this error:

{"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_eth0'"}

The log:

TASK [Ensuring netfilter-persistent Is Enabled and Starts On Reboot] **************************************************************************************************************************************
Wednesday 20 February 2019  15:12:06 -0800 (0:00:03.741)       0:00:12.074 **** 
ok: [rpi-k8s-1]

TASK [Setting Up IP Forwarding On Primary] ****************************************************************************************************************************************************************
Wednesday 20 February 2019  15:12:06 -0800 (0:00:00.765)       0:00:12.840 **** 
ok: [rpi-k8s-1]

TASK [Configuring Static IP On Primary] *******************************************************************************************************************************************************************
Wednesday 20 February 2019  15:12:07 -0800 (0:00:00.612)       0:00:13.453 **** 
ok: [rpi-k8s-1]

TASK [Updating /etc/hosts] ********************************************************************************************************************************************************************************
Wednesday 20 February 2019  15:12:09 -0800 (0:00:01.793)       0:00:15.246 **** 
fatal: [rpi-k8s-1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_eth0'"}
        to retry, use: --limit @/Volumes/Fifth/Backup/Softwares/Raspberry Pi/ansible-rpi-k8s-cluster/playbooks/deploy.retry

PLAY RECAP ************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
rpi-k8s-1                  : ok=6    changed=0    unreachable=0    failed=1   

Wednesday 20 February 2019  15:12:09 -0800 (0:00:00.372)       0:00:15.619 **** 
=============================================================================== 
Updating APT Cache --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.10s
Installing iptables-persistent --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.74s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 2.06s
Configuring Static IP On Primary ------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.79s
Ensuring netfilter-persistent Is Enabled and Starts On Reboot -------------------------------------------------------------------------------------------------------------------------------------- 0.77s
Setting Up IP Forwarding On Primary ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.61s
Updating /etc/hosts -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.37s
Fail When DHCP Scope Ending Is Not Correct --------------------------------------------------------------------------------------------------------------------------------------------------------- 0.03s
Checking To Make Sure Both DNSMasq and ISC-DHCP Are Not True --------------------------------------------------------------------------------------------------------------------------------------- 0.03s
Capturing The Current DHCP Scope Ending IP --------------------------------------------------------------------------------------------------------------------------------------------------------- 0.03s
Calculating The Required DHCP Scope Ending IP ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.03s

**Comment by mrlesmithjr** [comment]
@wpoosanguansit Did you get this resolved by chance? Sounds like #16 is the same issue.

**Comment by mrlesmithjr** [comment]
Curious if the interface naming on your setup and #16 are not `ethX`, but `enpXXX` now.

**Comment by wpoosanguansit** [comment]
@mrlesmithjr I have not been able to resolve the issue.  How do I change the interface name to enpXX then?

**Comment by mrlesmithjr** [comment]
I just ran into this issue recently as well, and for some reason it was related to not having the ethernet cable plugged in on the master node.

Closing this issue!
