### ISSUE TITLE
download.gluster.org cannot be resolved on slaves, but on master

### ISSUE THREAD

**Issue by dakoller** [mrlesmithjr/ansible-rpi-k8s-cluster#17]
I get

ok: [rpi-k8s-1]
fatal: [rpi-k8s-3]: FAILED! => {"changed": false, "msg": "Failed to connect to download.gluster.org at port 443: [Errno -3] Temporärer Fehler bei der Namensauflösung"}

...any idea why the master can resolve the url, but the slaves not?

Kind regards,

Daniel

**Comment by mrlesmithjr** [comment]
@dakoller Are you still experiencing this?

**Comment by mrlesmithjr** [comment]
I just saw this recently as well, seems to be an intermittent issue with DNSMasq on the master node. A quick `sudo systemctl restart dnsmasq.service` **SHOULD** resolve this.

Closing this out.
