### ISSUE TITLE
Kubernetes Package version conflicts

### ISSUE THREAD

**Issue by dakoller** [mrlesmithjr/ansible-rpi-k8s-cluster#18]
When trying to install the kubernetes packages I get 

"TASK [ansible-k8s : debian | Installing K8s Packages] *************************************************************************************************************************************
Sunday 28 April 2019  09:31:52 +0200 (0:00:00.061)       0:01:51.346 **********
failed: [rpi-k8s-1] (item=[u'kubelet', u'kubeadm', u'kubectl', u'kubernetes-cni']) => {"cache_update_time": 1556435223, "cache_updated": false, "changed": false, "item": ["kubelet", "kubeadm", "kubectl", "kubernetes-cni"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'kubelet' 'kubeadm' 'kubectl' 'kubernetes-cni'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed\n kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", **"The following packages have unmet dependencies:", " kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed", " kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed"]}**"

**Comment by mrlesmithjr** [comment]
@dakoller Thanks for reporting this. Have you had any luck since filing this? I will have to dig into this as time permits to see what is going on.

**Comment by aaronkjones** [comment]
I was able to get around this by changing k8s_version from 1.11.2 to 1.14.0. I did not try lower versions like 1.13.0.

**Comment by mrlesmithjr** [comment]
@dakoller Awesome! I am about due to rebuild my cluster soon, so I am assuming that I will run into issues.

**Comment by mrlesmithjr** [comment]
I have resolved this in the ansible-k8s role which is now a submodule.


Closing this issue.
