### ISSUE TITLE
dnsmasq resolver doesnt forward (intermittent)

### ISSUE THREAD

**Issue by mdmelo** [mrlesmithjr/ansible-rpi-k8s-cluster#9]
had issues resolving raspbian.raspberrypi.org from slaves (for installing NTP), rebooted master and then worked OK.  clients later tried to resolve download.gluster.org and couldnt.  rebooted master again and then worked OK.   Also tried using ISC DHCP instead of dnsmasq, not a better outcome.

**Comment by mrlesmithjr** [comment]
@mdmelo Thanks for reporting this. I have not seen this issue in numerous deployments; however, I would not be shocked if I saw the same thing when doing a new deployment. Which I have not done in a month or so which failed based on #8 . I will dig into this again here soon and see if I can duplicate the same issue.

**Comment by mdmelo** [comment]
ok thanks.  another issue i experienced was ansible timeout attempting sudo on the slaves.  i had to add 'raspberrypi' to /etc/hosts on all the slaves as sudo was trying to resolve the hostname and it was taking longer than ansible wanted to wait.  (i used strace on a slave to find the issue). i also modified the hosts template to keep that hostname.  i have no ansible experience so likely this is hackery...

thanks for making all your hard work available, this is a fun learning experience for me!

**Comment by mrlesmithjr** [comment]
I have resolved both of these issues in the latest changes.

Reference #17 

And for the SSH timeout I have increased the ssh timeout to `300` in `ansible.cfg`. I just ran into this issue recently as well.

Closing this issue out!
